domain: mrinalsave.github.io
url: https://mrinalsave.github.io
baseurl: ""
title: mrinal's digital archive
description: under construction (ദ്ദി˙ᗜ˙)

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/devlog/page:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: blog
      permalink: /devlog/:year/:month/:day/:title.html